all:
	make -C src --file MakefileCppUTest.make

test:
	make -C src --file MakefileCppUTest.make test

run:
	make -C src --file MakefileCppUTest.make run

clean:
	make -C src --file MakefileCppUTest.make clean

rebuild:
	make -C src --file MakefileCppUTest.make rebuild

rebuildt:
	make -C src --file MakefileCppUTest.make rebuildt


#Makefile debug options
filelist:
	make -C src --file MakefileCppUTest.make filelist

dirlist:
	make -C src --file MakefileCppUTest.make dirlist

flags:
	make -C src --file MakefileCppUTest.make flags

colortest:
	make -C src --file MakefileCppUTest.make colortest

help:
	make -C src --file MakefileCppUTest.make help
